name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy files to EC2
      uses: itynan/AiCyberLabs@prod
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.AICYBERLABS }}
        port: '22'
        source: "."
        target: "/home/ec2-user/myenv/bin/activate"

    - name: Execute remote SSH commands
      uses: itynan/AiCyberLabs@prod
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AICYBERLABS }}
        port: '22'
        script: |
          cd /path/to/remote/directory
          # Activate the virtual environment
          source venv/bin/activate
          # Restart the application (Adjust the command based on your setup)
          #sudo systemctl restart myapp.service
