---

name: auto-Deploy to AWS
on:
  push:
    branches:
      - prod
#terminal login key2
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -v -p ${{ runner.temp }}/.ssh
          echo "${{ secrets.AICBERLABS }}" > ${{ runner.temp }}/.ssh/aicyber
          chmod 600 ${{ runner.temp }}/.ssh/aicyber
          ssh-keyscan -v -H 3.15.32.33 >> ${{ runner.temp }}/.ssh/known_hosts
      - name: Deploy to EC2
        run: ssh -v -i ${{ runner.temp }}/.ssh/aicyber -o "StrictHostKeyChecking=no"
          ec2-user@3.15.32.33 'bash ~/deploy.sh'