name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWSCAPSTONEPRIVKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-ec2-public-ip >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: ssh -i ~/.ssh/id_rsa ec2-user@18.216.119.33 'deploy-command'
