name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy files to EC2
        uses: itynan/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AICYBERLABS }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/home/ec2-user/myenv/bin/activate"

      - name: Restart application
        uses: itynan/AiCyberLabs@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AICYBERLABS }}
          port: ${{ secrets.PORT }}
          script: |
            /home/ec2-user/myenv/bin/activate
            source venv/bin/activate
            # Restart your application here, e.g.:
            # For Flask:
            #   pkill -f flask
            #   nohup flask run --host=0.0.0.0 &
            # For Gunicorn:
            #   pkill gunicorn
            #   nohup gunicorn your_app:app -b 0.0.0.0:8000 &
