---

name: deploy to aws
on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: mkdir -v -p ${{ runner.temp }}/.ssh
          echo "${{ secrets.AWSCAPSTONEPRIVKEY }}" >
      - name: SSH key passthru
        run: ${{ runner.temp }}/.ssh/id_rsa
          chmod 600 ${{ runner.temp }}/.ssh/id_rsa
          ssh-keyscan -H 18.216.119.33 >> ${{ runner.temp }}/.ssh/known_hosts
          echo "endeding run"
      - name: Deploy to EC2
        run: echo "starting run2" ssh -i ${{ runner.temp }}/.ssh/id_rsa -o
          "StrictHostKeyChecking no" ec2-user@18.216.119.33
          'bash ~/deploy.sh' echo "ending run2"
